fix: large bbox
MapColonies/flat-earth pull request #13
Opened 2024-02-28 15:21 UTC by vitaligi

fixes a bug, in `findMinimalZoom`, once a bbox is given with one of it's axes larger than the tile size in the corresponding axis at the firts zoom level (0)

2024-02-29 12:39 UTC, shimoncohen commented on src/tiles/tiles.ts
> +export function findMinimalZoom(boundingBox: BoundingBox, referenceTileGrid: TileGrid = TILEGRID_WORLD_CRS84): Zoom | null {
Maybe `findMinimalZoomOfContainingTile`?
It feels a little complicated, maybe this means that the logic should be split?

2024-02-29 15:42 UTC, shimoncohen commented on src/tiles/tiles.ts
> +export function findMinimalZoom(boundingBox: BoundingBox, referenceTileGrid: TileGrid = TILEGRID_WORLD_CRS84): Zoom | null {
Please change function to `minimalBoundingTile` as we discussed.

2024-03-04 18:34 UTC, shimoncohen requested changes

2024-03-04 18:34 UTC, shimoncohen commented on tests/tiles/tiles.spec.ts
> +  it('should return correct tile starting at lookup at zoom 2 and moving to 0', () => {
Duplicate `at`.

2024-03-04 18:34 UTC, shimoncohen commented on tests/tiles/tiles.spec.ts
> +  it('should return correct tile starting at lookup at zoom 2 and moving to 0', () => {
This test is the same as the previous one, why not pass parameters to a unified test?

2024-03-04 18:34 UTC, shimoncohen commented on tests/tiles/tiles.spec.ts
> +  it('bounding box located on the edge of a tile grid should go one zoom level up', () => {
Please fix failing test.

2024-03-04 20:44 UTC, vitaligi commented on tests/tiles/tiles.spec.ts
> +  it('should return correct tile starting at lookup at zoom 2 and moving to 0', () => {
fixed

2024-03-04 20:54 UTC, vitaligi commented on tests/tiles/tiles.spec.ts
> +  it('bounding box located on the edge of a tile grid should go one zoom level up', () => {
fixed

2024-03-04 23:33 UTC, shimoncohen commented on tests/tiles/tiles.spec.ts
> +  it('bounding box located on the edge of a tile grid should go one zoom level up', () => {
Did you push the changes?

2024-03-05 10:32 UTC, shimoncohen approved these changes

2024-03-05 10:58 UTC, merged